name: pypi
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: abatilo/actions-poetry@v2.1.3
      - name: Config poetry
        run: poetry config experimental.new-installer false
      - name: Build dists
        run: make build
      - name: Pypi Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
